version: '3.8'

services:
  telegram-bot:
    build: ./bot
    container_name: server-monitor-bot
    volumes:
      - .//app/data
    restart: unless-stopped

  web-panel:
    image: python:3.11-slim
    container_name: server-monitor-web
    working_dir: /app
    volumes:
      - ./web:/app
      - ./data:/app/data
    ports:
      - "5000:5000"
    command: python app.py
    depends_on:
      - telegram-bot
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: server-monitor-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
    depends_on:
      - web-panel
    restart: unless-stopped